// react/basic/src/App.js
import React, { useState, useEffect } from "react";
import './App.css';
import nokori from "@nokori/js-sdk";
const nk = new nokori(import.meta.env.VITE_NOKORI_API_KEY);

function App() {
  const [loadingData, setLoadingData] = useState(true);
  const [data, setData] = useState([]);

  useEffect(() => {
    async function getData() {
      const {
        data: results, 
        error
      } = await nk.query.execute({
          queryId: '{{YOUR_QUERY_ID}}'
        })

      if (error) {
        console.error(error);
      }

      if(results && !error) {
        setData(results);
        setLoadingData(false);
      }
    }
    
    if (loadingData) {
      getData();
    }
  });

  return (
    <div className="App">
      <h1>React nokori Example</h1>
      <p>
        In this fictitious example, we are fetching customer orders from our database of soda orders at
        our soda shop.
      </p>
      <h2>Orders list</h2>
      {/* here you check if the state is loading otherwise if you wioll not call that you will get a blank page because the data is an empty array at the moment of mounting */}
      {
        loadingData && !data ? (
          <p>Loading Please wait...</p>
        ) : (
        // <Table columns={columns} data={data} />
        <table>
          <thead>
          <tr>
            <th>Order ID</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Customer Id</th>
          </tr>
          </thead>
          <tbody>
          { 
          !loadingData && data.map((order) => {
            return <tr key={order.orderId}>
              <td>{order.orderId}</td>
              <td>{order.productName}</td>
              <td>{order.quantity}</td>
              <td>{order.customerId}</td>
            </tr>
          })
          }
          </tbody>
        </table>
      )}
    </div>
  );
}

export default App;

// vue/vue3/basic/src/App.vue
<script setup lang="ts">
import { onMounted, reactive } from "vue";
import nokori from "@nokori/js-sdk";
const nk = new nokori(import.meta.env.VITE_NOKORI_API_KEY);

interface Orders {
  orderId: string;
  productName: string;
  quantity: number;
  customerId: string;
}

interface Data {
  orders: Orders[];
  isLoading: boolean;
}

const data: Data = reactive({
  orders: [],
  isLoading: true,
});

onMounted(async () => {
  const { data: orders, error } = await nk.query.execute({
    queryId: "{{YOUR_QUERY_ID}}",
  });

  if (error) {
    console.error(error);
    return;
  }
  data.orders = orders;
  data.isLoading = false;
});
</script>

<template>
  <header>
    <div id="wrapper">
      <h1 class="text-4xl font-bold">Vue3 nokori Example</h1>
      <p class="pt-4">
        In this fictitious example, we are fetching customer orders from our
        database of soda orders at our soda shop.
      </p>
      <h2 class="text-xl pt-4">Orders list</h2>

      <p v-if="data.isLoading">loading...</p>

      <table class="table-auto" v-if="!data.isLoading">
        <tr>
          <th>Order ID</th>
          <th>Product Name</th>
          <th>Quantity</th>
          <th>Customer Id</th>
        </tr>

        <tr v-for="order of data.orders" v-bind:key="order.orderId">
          <td>{{ order.orderId }}</td>
          <td>{{ order.productName }}</td>
          <td>{{ order.quantity }}</td>
          <td>{{ order.customerId }}</td>
        </tr>
      </table>
    </div>
  </header>
</template>

<style scoped>
header {
  line-height: 1.5;
}

#wrapper {
  padding: 20px;
}

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 40%;
}

table td,
table th {
  border: 1px solid #dddddd;
  text-align: right;
  padding: 8px;
}
</style>
